# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image:
  file: .gitpod.Dockerfile
tasks:
  - init:
      make build
    command: |
      gp sync-done build
      ./prometheus --config.file=documentation/examples/prometheus.yml
  - command: |
      cd web/ui/
      gp sync-await build
      unset BROWSER
      export DANGEROUSLY_DISABLE_HOST_CHECK=true
      npm start
    openMode: split-right
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9090
    onOpen: ignore
