# This dockerfile is multi target. Use DOCKER_BUILDKIT=1 when building and reference the target:
# --target=vendor with -o <host local path> to build image with the generated dependencies to copy and vendor on demand.
# --target=app to build actual application image.

# For the lack of the other official Google nodejs image, we use serverless project
# images to build the Prometheus frontent (https://cloud.google.com/docs/buildpacks/base-images).
ARG IMAGE_BUILD_NODEJS=us-central1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/nodejs22:latest@sha256:9e88442205b4c956ca4996c2be626db6ef412043182cdd620e741d0d5e14b6a6
ARG IMAGE_BUILD_GO=google-go.pkg.dev/golang:1.26.4@sha256:3444149d0a7e3f7cfb9c2db65f0f75676fe6ad04de3ce72674efb120c08dd1c1
ARG IMAGE_BASE_DEBUG=gcr.io/distroless/base-nossl-debian12:debug@sha256:2b89aea887933b8595f62c3d7e05a2718a0594e21e506952ce55b68b537f4fb6
ARG IMAGE_BASE=gke.gcr.io/gke-distroless/libc:gke_distroless_20260601.00_p0@sha256:1b74f92a381c5269d5018b08ce0464cfcb310b6b9b6d98767ba3300838483fc4

FROM ${IMAGE_BUILD_GO} AS gobase
WORKDIR /workspace
# Verify early if we have all we need.
RUN go version

FROM ${IMAGE_BUILD_NODEJS} AS nodebase
WORKDIR /workspace
# Changed to root,as normally it's underprivileged www-data user.
# For building stages it's fine to do it as root and have less complex scripts.
USER root
# Go, make, git, bzip2 are needed in Prometheus vendor and build steps, take Go
# from the gobase, rest from apt.
COPY --from=gobase /usr/local/go /usr/local/
ENV PATH="/usr/local/go/bin:${PATH}"
ENV UV_USE_IO_URING=0
ENV UV_THREADPOOL_SIZE=1
RUN apt-get update && apt-get -y install bzip2 make git
RUN corepack enable pnpm
RUN pnpm config set child-concurrency 1
# Verify early if we have all we need.
RUN npm version
RUN pnpm --version
RUN make -v
RUN git --version
RUN bzip2 --version
RUN go version

# --target=vendor
FROM gobase AS govendor
COPY . ./
ENV GOWORK=off
RUN go mod vendor

FROM nodebase AS nodevendor
COPY . ./
# On the nodebase image, the NODE_ENV is set to production, causing npm install
# to omit devDependencies. That would be normally preferred (much less packages
# vendored, avoiding security vuln. for deps used for tests), but Prometheus uses
# some devDependencies for normal build at the moment too e.g. @lezer/generator
# (custom build script), rollup, tsc (TypeScript) and probably more.
# Installing those manually later on is prone to errors, especially across
# different Prometheus versions.
# TODO(bwplotka): Consider moving those deps in upstream to non-dev lists.
ENV NODE_ENV="development"
RUN (cd web/ui && pnpm install) || [ -d web/ui/node_modules/vite ]
RUN (cd web/ui/react-app && pnpm install) || [ -d web/ui/react-app/node_modules/react ]

FROM scratch AS vendor
COPY --from=govendor /workspace/vendor vendor
COPY --from=nodevendor /workspace/web/ui/node_modules web/ui/node_modules
COPY --from=nodevendor /workspace/web/ui/mantine-ui/node_modules web/ui/mantine-ui/node_modules
COPY --from=nodevendor /workspace/web/ui/module/codemirror-promql/node_modules web/ui/module/codemirror-promql/node_modules
COPY --from=nodevendor /workspace/web/ui/react-app/node_modules web/ui/react-app/node_modules

# --target=app
# Compile the UI assets.
FROM nodevendor AS assets
RUN (make ui-build) || ( [ -d web/ui/static/react-app ] && [ -d web/ui/static/mantine-ui ] )
RUN scripts/compress_assets.sh

# Build the actual Go binary.
FROM gobase AS buildbase
ARG TARGETARCH
ARG TARGETOS
ARG BUILDARCH
COPY --from=assets /workspace ./
COPY --from=govendor /workspace/vendor vendor
ENV GOEXPERIMENT=boringcrypto
ENV CGO_ENABLED=1
ENV GOFIPS140=off
ENV GOTOOLCHAIN=local
ENV GOWORK=off
ENV GOARCH=${TARGETARCH}
ENV GOOS=${TARGETOS}
RUN if [ "${TARGETARCH}" = "arm64" ] && [ "${BUILDARCH}" != "arm64" ]; then \
      apt install -y --no-install-recommends \
        gcc-aarch64-linux-gnu libc6-dev-arm64-cross; \
      CC=aarch64-linux-gnu-gcc; \
    fi && \ 
    go build \
    -tags builtinassets -mod=vendor \
    -ldflags="-X github.com/prometheus/common/version.Version=$(cat VERSION) \
    -X github.com/prometheus/common/version.BuildDate=$(date --iso-8601=seconds)" \
    ./cmd/prometheus && \
    go build \
    -mod=vendor \
    -ldflags="-X github.com/prometheus/common/version.Version=$(cat VERSION) \
    -X github.com/prometheus/common/version.BuildDate=$(date --iso-8601=seconds)" \
    ./cmd/promtool

# Configure distroless base image like the upstream Prometheus image.
# Since the directory and symlink setup needs shell access, we need yet another
# intermediate stage.
FROM ${IMAGE_BASE_DEBUG} AS appbase

COPY documentation/examples/prometheus.yml  /etc/prometheus/prometheus.yml
RUN ["/busybox/sh", "-c", "mkdir -p /prometheus"]

FROM ${IMAGE_BASE} AS app

COPY --from=buildbase /workspace/prometheus /bin/prometheus
COPY --from=buildbase /workspace/promtool /bin/promtool
COPY --from=appbase --chown=nobody:nobody /etc/prometheus /etc/prometheus
COPY --from=appbase --chown=nobody:nobody /prometheus /prometheus
COPY LICENSE /LICENSE
COPY NOTICE /NOTICE

USER       nobody
EXPOSE     9090
VOLUME     [ "/prometheus" ]
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus" ]
