# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A example scrape configuration for running Prometheus with Uyuni.

scrape_configs:

  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Discover Uyuni managed targets to scrape.
  - job_name: 'uyuni'

    # Scrape Uyuni itself to discover new services.
    uyuni_sd_configs:
      - server: http://uyuni-project.org
        username: gopher
        password: hole
    relabel_configs:
      - source_labels: [__meta_uyuni_exporter]
        target_label: exporter
      - source_labels: [__meta_uyuni_groups]
        target_label: groups
      - source_labels: [__meta_uyuni_minion_hostname]
        target_label: hostname
      - source_labels: [__meta_uyuni_primary_fqdn]
        regex: (.+)
        target_label: hostname
      - source_labels: [hostname, __address__]
        regex: (.*);.*:(.*)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_uyuni_metrics_path]
        regex: (.+)
        target_label: __metrics_path__
      - source_labels: [__meta_uyuni_proxy_module]
        target_label: __param_module
