name: "Run Prombench"

on:
  issue_comment:                                 
    types:
      - created

env:
  CANCEL_BENCHMARK: "false"
  CLUSTER_NAME: prombench
  PROMETHEUS_IMAGE_REPOSITORY: gke.gcr.io/prometheus-engine/prometheus
  CREATE_CLUSTER: "true"
  DASHBOARD_ID: 8dc0ed11-c0bd-4fb3-9cdf-1ef8ae04bdad
  DISABLE_LOADGEN_QUERIER: "true"
  DOMAIN_NAME: ""
  GITHUB_ORG: ${{ github.repository_owner }} # GoogleCloudPlatform
  GITHUB_REPO: ${{ github.event.repository.name }} # prometheus
  GITHUB_STATUS_TARGET_URL: ""
  GKE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GRAFANA_ADMIN_PASSWORD: admin
  LAST_COMMIT_SHA: ${{ github.event.client_payload.LAST_COMMIT_SHA }}
  OAUTH_TOKEN: ""
  PR_NUMBER: ${{github.event.issue.number}}
  PROVIDER: gke
  RELEASE: ${{ github.event.repository.default_branch }} # e.g. main / release-X.Y.Z-gmp / etc.
  SERVICEACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICEACCOUNT_CLIENT_EMAIL }}
  WH_SECRET: ""
  ZONE: us-east4-a

jobs:
  benchmark:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/prombench')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - name: 'User Verification'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENTER: ${{ github.event.comment.user.login }}
        run: |
          COMMENTER_PERMISSION=$(curl --silent -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${GITHUB_ORG}/${GITHUB_REPO}/collaborators/${COMMENTER}/permission | jq --raw-output .permission)
          
          if ! ([ "${COMMENTER_PERMISSION}" == "admin" ] || [ "${COMMENTER_PERMISSION}" == "write" ])
          then
            echo "${COMMENTER} does not have admin or write privileges. Therefore cannot execute the benchmark command."
            
            curl --silent -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_ORG}/${GITHUB_REPO}/issues/${PR_NUMBER}/comments \
            --data '{ "body": "'${COMMENTER}' does not have admin or write privileges. Therefore cannot execute the benchmark command." }'
            exit 1
          fi

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      
      - name: 'Set environment variables based on the triggered action'
        run: |
          COLLECTOR_TAG_OR_CANCEL=$(echo ${{ github.event.comment.body }} | head -n 1 | awk '{ print $2 }')

          if [ "${COLLECTOR_TAG_OR_CANCEL}" == "cancel" ]
          then
            
            echo "Cancelling the benchmark run for PR #${PR_NUMBER}."
            CANCEL_BENCHMARK="true"
            echo "CANCEL_BENCHMARK=${CANCEL_BENCHMARK}" >> $GITHUB_ENV

          else
            
            echo "GMP Collector Tag: ${COLLECTOR_TAG_OR_CANCEL}"

            function get_default_collector_tag() {
              DEFAULT_COLLECTOR_TAG=$(gcloud container images list-tags ${PROMETHEUS_IMAGE_REPOSITORY} --sort-by=UPDATE_TIME,TAGS | tail -1 | awk '{ print $2 }')
            }

            if [[ $COLLECTOR_TAG_OR_CANCEL == '' ]]
            then
              echo "Since the collector version is missing, the latest one would be used."
              get_default_collector_tag
              echo "PROMETHEUS_IMAGE_VERSION=${DEFAULT_COLLECTOR_TAG}" >> $GITHUB_ENV
              export PROMETHEUS_IMAGE_VERSION="${DEFAULT_COLLECTOR_TAG}"
            else
              GCLOUD_TAG=$(gcloud container images list-tags --filter="tags:${COLLECTOR_TAG_OR_CANCEL}" --format=json ${PROMETHEUS_IMAGE_REPOSITORY})
              if [[ "$GCLOUD_TAG" == "[]" ]]
              then
                echo "The ${PROMETHEUS_IMAGE_REPOSITORY} image does not have the ${COLLECTOR_TAG_OR_CANCEL} tag. Hence, this run will use the default latest tag."
                DEFAULT_COLLECTOR_TAG=$(get_default_collector_tag)
                echo "PROMETHEUS_IMAGE_VERSION=${DEFAULT_COLLECTOR_TAG}" >> $GITHUB_ENV
                export PROMETHEUS_IMAGE_VERSION="${DEFAULT_COLLECTOR_TAG}"
              else
                echo "PROMETHEUS_IMAGE_VERSION=${COLLECTOR_TAG_OR_CANCEL}" >> $GITHUB_ENV
                export PROMETHEUS_IMAGE_VERSION="${COLLECTOR_TAG_OR_CANCEL}"
              fi
            fi
            
            echo "The release/base GMP Collector's tag is set to: ${PROMETHEUS_IMAGE_VERSION}."

          fi

      - name: 'Post a comment to the PR upon triggering the benchmark run'
        if: env.CANCEL_BENCHMARK == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MONITORING_DASHBOARD_URL="https://console.cloud.google.com/monitoring/dashboards/builder/${DASHBOARD_ID};duration=PT15M"
          
          COMMENT_MSG="This benchmark run compares this PR (https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/pull/${PR_NUMBER}) with version \`${PROMETHEUS_IMAGE_VERSION}\` of the [GMP Collector](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed).\n\nAfter a successful deployment, the benchmarking results can be viewed on the [Cloud Monitoring Dashboard](${MONITORING_DASHBOARD_URL}).\n\nTo cancel or stop the benchmark run, comment \`/prombench cancel\` on this PR."

          curl --silent -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_ORG}/${GITHUB_REPO}/issues/${PR_NUMBER}/comments \
            --data '{ "body": "'"${COMMENT_MSG}"'" }'
          
      - name: 'Adding the prombench label to the PR'
        if: env.CANCEL_BENCHMARK == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --silent -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_ORG}/${GITHUB_REPO}/issues/${PR_NUMBER}/labels \
            -d '{"labels":["prombench"]}'
      
      - name: 'Check if the cluster exists'
        run: |
          if RETURN=$(gcloud container clusters describe "${CLUSTER_NAME}" --project="${GKE_PROJECT_ID}" --location="${ZONE}" >/dev/null 2>&1)
          then
            CREATE_CLUSTER="false"
            echo "CREATE_CLUSTER=${CREATE_CLUSTER}" >> $GITHUB_ENV
            echo "The cluster (name: ${CLUSTER_NAME}) already exists. Therefore, skipping cluster creation."
          else
            CREATE_CLUSTER="true"
            echo "CREATE_CLUSTER=${CREATE_CLUSTER}" >> $GITHUB_ENV
            echo "The cluster (name: ${CLUSTER_NAME}) does not exist, the cluster will get created before creating the nodes and triggering the benchmark process."
          fi

      
      - name: 'Create the cluster'
        if: env.CREATE_CLUSTER == 'true'
        uses: docker://ghcr.io/googlecloudplatform/prometheus-test-infra/prombench:latest
        with:
            args: make cluster_create;
      
      - name: 'Apply the cluster resources (to the main node)'
        if: env.CREATE_CLUSTER == 'true'
        uses: docker://ghcr.io/googlecloudplatform/prometheus-test-infra/prombench:latest
        with:
            args: make cluster_resource_apply;
      
      - name: 'Create the nodes'
        if: env.CANCEL_BENCHMARK == 'false'
        uses: docker://ghcr.io/googlecloudplatform/prometheus-test-infra/prombench:latest
        with:
            args: >-
              make clean;
              until make all_nodes_deleted; do echo "Waiting for nodepools to be deleted"; sleep 10; done;
              make node_create;
      
      - name: 'Apply the node resources (benchmark-related deployments)'
        if: env.CANCEL_BENCHMARK == 'false'
        uses: docker://ghcr.io/googlecloudplatform/prometheus-test-infra/prombench:latest
        with:
            args: make resource_apply;
      
      - name: 'Delete the nodes'
        if: env.CANCEL_BENCHMARK == 'true'
        uses: docker://ghcr.io/googlecloudplatform/prometheus-test-infra/prombench:latest
        with:
            args: make clean;

      - name: 'Post a comment to the PR upon cancelling the benchmark run'
        if: env.CANCEL_BENCHMARK == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT_MSG="Cancelling the benchmark run (for this PR)."

          curl --silent -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_ORG}/${GITHUB_REPO}/issues/${PR_NUMBER}/comments \
            --data '{ "body": "'"${COMMENT_MSG}"'" }'
